FROM jupyter/datascience-notebook:2fd856878b83
MAINTAINER Takao Sumitomo
LABEL OBJECT="My Jupyter Notebook"

RUN conda install --quiet --yes -c anaconda pivottablejs
RUN conda install -c conda-forge google-cloud-bigquery
